// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mcp/server.proto

package mcp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientState int32

const (
	ClientState_HANDSHAKING ClientState = 0
	ClientState_STATUS      ClientState = 1
	ClientState_LOGIN       ClientState = 2
	ClientState_PLAY        ClientState = 3
)

var ClientState_name = map[int32]string{
	0: "HANDSHAKING",
	1: "STATUS",
	2: "LOGIN",
	3: "PLAY",
}
var ClientState_value = map[string]int32{
	"HANDSHAKING": 0,
	"STATUS":      1,
	"LOGIN":       2,
	"PLAY":        3,
}

func (x ClientState) String() string {
	return proto.EnumName(ClientState_name, int32(x))
}
func (ClientState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_server_97d038bfe28487a3, []int{0}
}

type Handshake struct {
	ProtocolVersion      uint64   `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handshake) Reset()         { *m = Handshake{} }
func (m *Handshake) String() string { return proto.CompactTextString(m) }
func (*Handshake) ProtoMessage()    {}
func (*Handshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_97d038bfe28487a3, []int{0}
}
func (m *Handshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handshake.Unmarshal(m, b)
}
func (m *Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handshake.Marshal(b, m, deterministic)
}
func (dst *Handshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handshake.Merge(dst, src)
}
func (m *Handshake) XXX_Size() int {
	return xxx_messageInfo_Handshake.Size(m)
}
func (m *Handshake) XXX_DiscardUnknown() {
	xxx_messageInfo_Handshake.DiscardUnknown(m)
}

var xxx_messageInfo_Handshake proto.InternalMessageInfo

func (m *Handshake) GetProtocolVersion() uint64 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func init() {
	proto.RegisterType((*Handshake)(nil), "server.Handshake")
	proto.RegisterEnum("server.ClientState", ClientState_name, ClientState_value)
}

func init() { proto.RegisterFile("mcp/server.proto", fileDescriptor_server_97d038bfe28487a3) }

var fileDescriptor_server_97d038bfe28487a3 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x4d, 0x2e, 0xd0,
	0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0,
	0x94, 0xcc, 0xb8, 0x38, 0x3d, 0x12, 0xf3, 0x52, 0x8a, 0x33, 0x12, 0xb3, 0x53, 0x85, 0x34, 0xb9,
	0x04, 0xc0, 0xb2, 0xc9, 0xf9, 0x39, 0xf1, 0x40, 0xc9, 0xe2, 0xcc, 0xfc, 0x3c, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0x96, 0x20, 0x7e, 0x98, 0x78, 0x18, 0x44, 0x58, 0xcb, 0x9e, 0x8b, 0xdb, 0x39, 0x27,
	0x33, 0x35, 0xaf, 0x24, 0xb8, 0x24, 0xb1, 0x24, 0x55, 0x88, 0x9f, 0x8b, 0xdb, 0xc3, 0xd1, 0xcf,
	0x25, 0xd8, 0xc3, 0xd1, 0xdb, 0xd3, 0xcf, 0x5d, 0x80, 0x41, 0x88, 0x8b, 0x8b, 0x2d, 0x38, 0xc4,
	0x31, 0x24, 0x34, 0x58, 0x80, 0x51, 0x88, 0x93, 0x8b, 0xd5, 0xc7, 0xdf, 0xdd, 0xd3, 0x4f, 0x80,
	0x49, 0x88, 0x83, 0x8b, 0x25, 0xc0, 0xc7, 0x31, 0x52, 0x80, 0xd9, 0x89, 0x35, 0x8a, 0x19, 0xe8,
	0xa8, 0x24, 0x36, 0xb0, 0xc1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0x20, 0x31, 0x21,
	0xa2, 0x00, 0x00, 0x00,
}
